---
title: "regression_tree_forest"
output: html_document
date: "2025-10-29"
---

## Data Visualisation & Manipulation

```{r}
# import 
restaurant_revenue <- read.csv("~/Documents/fac/M2/adv_machine_learning/project/data/restaurant_revenue.csv", stringsAsFactors=TRUE)
```

```{r}
head(restaurant_revenue)
```
```{r}
str(restaurant_revenue)
```
```{r}
table(is.na(restaurant_revenue))
```

```{r}
# transforming variable Promotions into factor 
restaurant_revenue$Promotions[restaurant_revenue$Promotions == 0] <- 'No'
restaurant_revenue$Promotions[restaurant_revenue$Promotions == 1] <- 'Yes'
restaurant_revenue$Promotions <- as.factor(restaurant_revenue$Promotions)
```

## Regression tree

```{r}
# libraries
library(rpart) 
library(rpart.plot) 
library(caret)
```

```{r}
set.seed(123)

# split train / test subsets 
train_index = createDataPartition(restaurant_revenue$Monthly_Revenue, p = 0.7, list = FALSE)
train_data = restaurant_revenue[train_index, ]
test_data = restaurant_revenue[-train_index, ]

# fit max tree
max_tree <- rpart(Monthly_Revenue ~. , data = train_data, cp = 0)
rpart.plot(max_tree)

# compute complexity 
cpOpt = max_tree$cptable[which.min(max_tree$cptable[,4]),1]
plotcp(max_tree) 
abline(v = which.min(max_tree$cptable[,4]), col = "red", lty = 2)

# fit pruned tree
pruned_tree = rpart(Monthly_Revenue ~. , data = train_data, cp = cpOpt)
rpart.plot(pruned_tree)
```
```{r}
# create the variable importance dataframe
x = sort(pruned_tree$variable.importance)
df_importance = data.frame(Variable = factor(names(x), levels = names(x)), 	Importance = as.numeric(x))

# plot
ggplot(df_importance, aes(x = Importance, y = Variable)) +
geom_col(fill = "#6bafd6") +
  labs(title = "Variables Importance", x = "Variable importance", size = 0.1) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 10)) 

```

```{r}
# predict using pruned tree
monthly_revenue_pred <- predict(pruned_tree, newdata = test_data)

# computing MSE, RMSE, COEFF OF DETERMINATION (R2)
mse <- mean((test_data$Monthly_Revenue - monthly_revenue_pred)^2)
rmse <- sqrt(mse)
r2 <- 1 - sum((test_data$Monthly_Revenue - monthly_revenue_pred)^2) / 
             sum((test_data$Monthly_Revenue - mean(test_data$Monthly_Revenue))^2)

# print 
cat("MSE of pruned tree:", mse, "\n")
cat("RMSE of pruned tree:", rmse, "\n")
cat("R2 of pruned tree:", r2, "\n")

# plot 
predVSactual_pruned <- 
ggplot(data = data.frame(test_data$Monthly_Revenue, monthly_revenue_pred), 
       aes(x = test_data$Monthly_Revenue, y = monthly_revenue_pred)) +
  geom_point(color = "#6bafd6", size = 2) + 
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +
  labs(title = "A. Pruned Tree", x = "", y = "") +
  #labs(title = "Predicted vs Actual Monthly Revenue",
       #x = "Actual Monthly Revenue",
       #y = "Predicted Monthly Revenue") +
  theme_minimal()
```

```{r}
# predict using max tree
monthly_revenue_pred_max <- predict(max_tree, newdata = test_data)

# computing MSE, RMSE, COEFF OF DETERMINATION (R2)
mse <- mean((test_data$Monthly_Revenue - monthly_revenue_pred_max)^2)
rmse <- sqrt(mse)
r2 <- 1 - sum((test_data$Monthly_Revenue - monthly_revenue_pred_max)^2) / 
             sum((test_data$Monthly_Revenue - mean(test_data$Monthly_Revenue))^2)

# print 
cat("MSE of pruned tree:", mse, "\n")
cat("RMSE of pruned tree:", rmse, "\n")
cat("R2 of pruned tree:", r2, "\n")

# plot 
predVSactual_max <-
ggplot(data = data.frame(test_data$Monthly_Revenue, monthly_revenue_pred_max), 
       aes(x = test_data$Monthly_Revenue, y = monthly_revenue_pred_max)) +
  geom_point(color = "#6bafd6", size = 2) + 
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +
  labs(title = "B. Full Tree", x = "", y = "") +
  #labs(title = "Predicted vs Actual Monthly Revenue",
       #x = "Actual Monthly Revenue",
       #y = "Predicted Monthly Revenue") +
  theme_minimal()
```

```{r}
library(ggpubr)

# plot figure 
predictedVSactual_fig <- 
  ggarrange(predVSactual_pruned, predVSactual_max, ncol = 2)
annotate_figure(predictedVSactual_fig, 
                top = "Predicted vs Actual Monthly Revenue", 
                left = "Predicted Monthely Revenue", 
                bottom = "Actual Monthely Revenue", 
                fig.lab.face = "bold")
```

# Regression forest 
```{r}

```
